### ISSUE TITLE
可以设置默认的省份简称吗？

### ISSUE THREAD

**Issue by pandaTED** [Downeystark/licensePlate#2]
用户一打开页面，就填好一个‘鲁’，然后用户完成剩下的输入。

**Comment by Downeystark** [comment]
可以在 var demo1 = new licensePlate(); 之后 使用
demo1.step = 1;
demo1.value = ['鲁'];
input默认value 鲁
搞定

**Comment by pandaTED** [comment]
好的，谢谢
