### ISSUE TITLE
初始化车牌号的方法没起作用，有什么办法初始化

### ISSUE THREAD

**Issue by glinxx** [Downeystark/licensePlate#4]
我试过2种初始化车牌号的方法都没作用
1.在licensePlates对象new的时候设置value值没反应
2.初始化之后再赋值也没用
licensePlates.value = '粤QJ5CH2'.split('');

**Comment by glinxx** [comment]
解决了，用了比较传统的方法

var car_no_array = '{{car_no}}'.split('');
var car_no_nodes = $(".car-plate")
$.each(car_no_nodes,function(i, item){
  $(item).val(car_no_array[i])
});

**Comment by Downeystark** [comment]
你是要设置默认值？

**Comment by Downeystark** [comment]
> 解决了，用了比较传统的方法
> 
> var car_no_array = '{{car_no}}'.split('');
> var car_no_nodes = $(".car-plate")
> $.each(car_no_nodes,function(i, item){
> $(item).val(car_no_array[i])
> });
你可以看看这个，车牌选择分成很多步，设置默认值后还需要设置相应的步数
https://github.com/Downeystark/licensePlate/issues/2
